//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedKernel.Properties.Application.PipelineBehaviors.LoggingBehavior {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedKernel.Properties.Application.PipelineBehaviors.LoggingBehavior.LanguageRes" +
                            "ources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correlativo: {0} - Hora de logeo: {1} | Error de lógica de negocio arrojado mientras se manejaba {2} con mensaje: {3} y codigo de estado: {4}..
        /// </summary>
        internal static string BussinessExceptionLog {
            get {
                return ResourceManager.GetString("BussinessExceptionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fallos.
        /// </summary>
        internal static string FailureState {
            get {
                return ResourceManager.GetString("FailureState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correlativo: {0} - Hora de logeo: {1} | Operación de manejo de {2} completada con {3}..
        /// </summary>
        internal static string FinalLog {
            get {
                return ResourceManager.GetString("FinalLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correlativo: {0} - Hora de logeo: {1} | Iniciando manejo de {2}..
        /// </summary>
        internal static string InitialLog {
            get {
                return ResourceManager.GetString("InitialLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correlativo: {0} - Hora de logeo: {1} | Terminado manejo de {2}, respuesta recibida correctamente..
        /// </summary>
        internal static string SuccessLog {
            get {
                return ResourceManager.GetString("SuccessLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exito.
        /// </summary>
        internal static string SuccessState {
            get {
                return ResourceManager.GetString("SuccessState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correlativo: {0} - Hora de logeo: {1} | Excepción de tipo {2} arrojada mientras se manejaba {3} con mensaje: {4}..
        /// </summary>
        internal static string UnhandledExceptionLog {
            get {
                return ResourceManager.GetString("UnhandledExceptionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correlativo: {0} - Hora de logeo: {1} | Error de validación arrojado mientras se manejaba {2}..
        /// </summary>
        internal static string ValidationExceptionLog {
            get {
                return ResourceManager.GetString("ValidationExceptionLog", resourceCulture);
            }
        }
    }
}
